

services:
  postgres:
    image: postgres:15
    container_name: revenue_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: revenue
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: revenue_redis
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: revenue-api:latest
    container_name: revenue_api
    depends_on:
      - postgres
      - redis
    env_file:
      - .env                      # <-- load all variables from .env
    ports:
      - "8080:8080"

volumes:
  postgres_data: